name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore HelloWorld_WinFormsApp.sln 
    - name: Build
      run: dotnet build HelloWorld_WinFormsApp.sln --no-restore
    - name: Test
      run: dotnet test HelloWorld_WinFormsApp.sln --no-build --verbosity normal
    - name: Super-Linter
      uses: github/super-linter@v4.9.5

